export const CONSTANTS = {
  HINTS_EASY: 3,
  HINTS_INTERMEDIATE: 0,
  HINTS_HARD: 0,
  TIME_SECONDS_EASY: 0,
  TIME_SECONDS_INTERMEDIATE: 90,
  TIME_SECONDS_HARD: 60,
  LIFES_EASY: 3,
  LIFES_INTERMEDIATE: 1,
  LIFES_HARD: 1,
  MAX_SCORE: 15,
  INITIAL_SCORE: 0,
  GREET_INTERVAL: 7500,
} as const;
