export const questionIntroductions = [
  "You're cruising through, and it's time for another challenge! Can you keep the momentum?",
  "Brilliant work so far! Let's dive into the next one and keep the good times rolling.",
  "You're proving to be quite the quiz champion! Ready for the next brain-teaser?",
  "Impressive! The next question awaits, and it's sure to be a thrilling one.",
  "Your knowledge is shining bright! Ready for the next dazzling question?",
  "Buckle up, you're on a winning streak! Let's see if it continues with the next question.",
  "Wow, you're nailing it! Can you conquer the next challenge on your quest to a million?",
  "You're doing awesome! Time for the next adventure into the world of questions.",
  "Your success is infectious! Get ready for the next dose of trivia.",
  "The game's heating up! Are you up for the next spicy question?",
  "You're making it look easy! The next question is just around the corner.",
  "On a roll, aren't you? Let's keep the momentum going with the next one.",
  "You're unstoppable! Time for the next question to put your knowledge to the test.",
  "Impressively good! Get ready for the next question, where the stakes are higher.",
  "You're on fire! The next question promises to be just as sizzling.",
  "You're leaving a trail of correct answers behind! Ready for the next stop?",
  "You're rocking this quiz! The next question is your next chance to shine.",
  "Unstoppable! Are you ready to face the next thrilling challenge?",
  "You're making it look like a breeze! Let's see how you handle the next one.",
  "Your journey to a million continues! The next question is waiting for your genius.",
  "You're making it look easy! Let's see if you can handle this curveball.",
  "Impressive! You're on a roll. Ready for the next challenge?",
  "You've got the Midas touch! Can you turn this question into gold?",
  "You're the real deal! Are you up for the next question",
  "You're a question-slaying superstar! Next up, another challenge.",
  "You're like a trivia tornado! Time to sweep through the next one.",
  "You're a quiz wizard! Time for your next magical question.",
  "You're like a quiz champ! Ready for the next round?",
  "You're the quiz's MVP! Let's see if you can score big on the next question.",
];

export const gameStartInvitations = [
  "The clock is ticking! Hurry up and let's start the game!",
  "Time's a-wasting! Let's dive into the action right away!",
  "The excitement is building! Don't keep us waiting. Start the game now!",
  "It's showtime! Get ready to answer some questions and win big!",
  "The hot seat is calling your name! Let's not waste a moment. Start the game!",
  "The million-dollar adventure awaits! Let's kick it off with a bang!",
  "The audience is eager, and so are we! Start the game and prove your knowledge!",
  "Don't keep the excitement on hold! Hit that button and let's begin!",
  "The suspense is killing us! Start the game, and let's find our next millionaire!",
  "The stage is set, and you're the star! Start the game and shine brightly!",
  "Ready to become a millionaire? Start now and make it happen!",
  "No time like the present! Start the game and let the journey begin!",
  "The opportunity of a lifetime is waiting! Start the game and seize it!",
  "The game is yours for the taking! Start now and show us what you've got!",
  "It's your moment to shine! Start the game, and let's make it memorable!",
  "The countdown is on! Start the game, and let's make every second count!",
  "The jackpot is within reach! Start the game, and let's aim for the stars!",
  "Time to show your stuff! Start the game, and let's make it legendary!",
  "Don't keep your fans waiting! Start the game and give them a show!",
  "Adventure awaits! Start the game, and let's embark on a journey to riches!",

  "Ready to unlock your fortune? Join me on Who Wants to Be a Millionaire and prove you're the ultimate brainiac!",
  "Imagine the rush of winning life-changing wealth. Will you seize the $1 million prize on Who Wants to Be a Millionaire?",
  "Become a legend! Claim the millionaire title right in front of you.",
  "Learn, laugh, and earn on Who Wants to Be a Millionaire. Let's create an unforgettable experience together.",
  "I'll support you with lifelines. Conquer Who Wants to Be a Millionaire with the crowd cheering you on.",
  "Picture the applause, the triumph. The millionaire moment awaits you.",
  "Play Who Wants to Be a Millionaire and join the millionaire club.",
  "Dare to win! Rise to greatness on Who Wants to Be a Millionaire.",
  "Picture this: the moment of truth. Will you walk away with a million-dollar smile? Join Who Wants to Be a Millionaire and find out.",
  "Are you ready to ignite your fortune? Step into the ultimate challenge that awaits, where brilliance and wealth collide.",
  "Unleash your inner genius and claim the grand prize that awaits those who dare to conquer the ultimate game of knowledge and wealth.",
  "Picture yourself on the edge of victory, facing mind-bending challenges that can lead to a life-altering fortune. Will you seize the opportunity?",
  "Join the prestigious league of those who have cracked the code to success, where wisdom and riches intertwine. Your moment to shine is here.",
  "It's time to challenge your limits, push the boundaries, and embark on a journey that holds the key to unlocking extraordinary wealth.",
  "Dare to rewrite your destiny by stepping into the realm of high-stakes challenges, where your intellect can pave the way to unimaginable riches.",
  "Seize the opportunity to redefine what's possible. Embark on a quest that promises not just wealth, but a legacy that will be remembered for ages.",
  "Harness the power of knowledge and let it propel you towards a future brimming with opulence. Your path to abundance begins now.",
  "Break free from the ordinary and set your sights on a realm where dreams become reality. Will you grasp the golden opportunity that awaits?",
  "Embrace the thrill of the unknown, as you face electrifying trials that can lead to a life of luxury. The choice is yours.",
];
